### ISSUE TITLE
[Enhancement] [Rules Screen]: Design for 4 rules in Rules Screen 

### ISSUE THREAD

**Issue by ntvkhoasgt** [pikachu404/Quiz-App#4]
@hellosagar 
Would you like let me contribute the Rules screen? I saw this project seem like available to Hacktoberfest 2021

**Idea detail:**
I will create 4 screen to 4 rules screen:
- The Quiz will contain 5 randomized questions.
- Every correct answer scores you 5 points.
- Every wrong answer deduct you 2 points.
- Your results will be saved and will be accumulated in your history.

**Features:** 
- User can swipe to check the rules.

**Tech:**
- Add image for single rules, add radio button group to locate position
- Create 4 activity_rules

**Sketch:**
![image](https://user-images.githubusercontent.com/67872483/136733634-13e1920c-9237-4858-a226-72670082cdaf.png)

**Comment by ntvkhoasgt** [comment]
@hellosagar 
If you had any recommend. Please tell me 🙇

**Comment by hellosagar** [comment]
This idea sounds good. Lets implement it

**Comment by hellosagar** [comment]
Resolved in this PR by you - [Modify Rules Screen #5](https://github.com/hellosagar/Quiz-App/pull/5)
